name: Deploy backend to Heroku

on:
  workflow_call:
    secrets:
      HEROKU_APP_NAME:
        required: true
      HEROKU_API_KEY:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        run: |
          echo "Authenticating with Heroku..."
          echo "${{ secrets.HEROKU_API_KEY }}" | heroku auth:token
          heroku auth:whoami
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Set up Heroku Git Remote
        run: |
          echo "Setting up Heroku remote..."
          if ! git remote | grep -q "heroku"; then
            git remote add heroku "https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git"
          fi
          git remote -v  # Debugging: List remotes

      - name: Push Backend to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Setting up Git credentials..."
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          echo "Setting up authentication..."
          HEROKU_GIT_URL="https://heroku:$HEROKU_API_KEY@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git"
          git remote set-url heroku "$HEROKU_GIT_URL"

          echo "Checking remotes..."
          git remote -v  # Debugging: Ensure the remote exists

          echo "Pushing to Heroku..."
          git subtree push --prefix backend heroku main
