name: Main Workflow

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Linter
        run: echo "Running linting checks..." # Currently dont have a linter

  test:
    runs-on: ubuntu-latest
    env:
      TEST_PIPELINE: "True"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run Tests
        run: pytest

  # deploy_backend:
  #   env:
  #     TEST_PIPELINE: "False"
  #   needs: [lint, test] # Deploy backend after lint and test
  #   uses: ./.github/workflows/deploy.yml
  #   secrets:
  #     HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}




  deploy_backend:
    env:
      TEST_PIPELINE: "False"
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Deployment Variables
        if: env.TEST_PIPELINE == 'False'
        run: |
          echo "Creating deployment variables..."
      - name: Deploy Application
        uses: ./.github/workflows/deploy.yml
        secrets:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}